# <- Information ->

# The plugin was created to set the format of the chat.
# The whole thing is open source on my github (https://github.com/MiSkynet)
# If something breaks, the config.yml can simply be deleted and the plugin reloaded.

# <- Configurations ->

# The appearance of the chat can be determined here
# These placeholders can be used here:
# %player% returns the player name
# %message% returns the message
# %prefix% returns the players prefix (LuckPerms related)
chat-format: "%player% §8» §f%message%"

# With this option you can visually customize your message in the chat 
# with '&' + <color code>
# (If this setting is activated, everyone can visually customize their message)
allow-chat-color: true